name: Deploy

on:
  push:
    branches:
      - master
      - test

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Trigger deploy
        run: |
          curl --fail-with-body --silent --show-error -X POST ${{ secrets.HOOKURL }} -H "X-Key: ${{ secrets.HOOKSECRET }}"
